<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/12.0.2">
  <PropertyGroup>
    <Authors>Nexai</Authors>
    <Version>2.3.2.0</Version>
    <AssemblyVersion>2.3.2.0</AssemblyVersion>
    <DalamudLibPath>$(USERPROFILE)\Desktop\DalamudTW\</DalamudLibPath>
    <AssemblySearchPaths>$(DalamudLibPath);{GAC};{TargetFrameworkDirectory};{RawFileName}</AssemblySearchPaths>
    <Description>Free Company Chest Helper. Automate deposits, withdrawals, organization, crystals, workshop project pulls, and custom item lists.</Description>
    <Copyright></Copyright>
    <PackageProjectUrl>https://github.com/Nexaii/FCCH</PackageProjectUrl>
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="FCCH.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Completion.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <Target Name="PackageRelease" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
    <MakeDir Directories="$(ProjectDir)releases" />
    <ZipDirectory SourceDirectory="$(OutputPath)" DestinationFile="$(ProjectDir)releases\$(AssemblyName).zip" Overwrite="true" />
    <Message Importance="High" Text="Release ZIP created: releases\$(AssemblyName).zip" />
  </Target>

</Project>
